# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '14.x'
  displayName: 'Install Node.js'

- script: |
    echo "Hello, GitHub!"
    echo "Hello, GitHub!" > index.html
  displayName: 'Create HTML file'

- script: |
    cat index.html
  displayName: 'Display HTML file content'